apiVersion: v1
kind: Service
metadata:
 name: wordpress
 labels:
   app: wordpress
spec:
 ports:
   - port: 8080
 selector:
   app: wordpress-app
 type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: wordpress
 labels:
   app: wordpress
spec:
 selector:
   matchLabels:
     app: wordpress
 strategy:
   type: Recreate
 template:
   metadata:
     labels:
       app: wordpress
   spec:
     containers:
     - image: wordpress:6.2.1-apache
       name: wordpress
       ports:
       - containerPort: 80
         name: wordpress